### ISSUE TITLE
CursorNotFound: cursor id '125740954290' not valid at server

### ISSUE THREAD

**Issue by rhiswell** [ccreimondo/visual-ip#1]
Traceback (most recent call last):
 File "grap_ip_from_awstats.py", line 114, in main
   merge(2015, months)
 File "grap_ip_from_awstats.py", line 87, in merge
   for record in pcoll.find():
 File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 983, in next
   if len(self.__data) or self._refresh():
 File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 925, in _refresh
   self.__id))
 File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 839, in __send_message
   codec_options=self.__codec_options)
 File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 110, in _unpack_response
   cursor_id)
CursorNotFound: cursor id '125740954290' not valid at server

Duration: 0:37:26.956077

**Comment by rhiswell** [comment]
http://api.mongodb.org/python/current/faq.html#how-do-i-change-the-timeout-value-for-cursors
